import Head from "next/head"
import { useQuery } from "urql"
import { PRODUCT_QUERY } from "../lib/query"
import Image from "next/image"
import { Gallery } from "../styles/Gallery"

// stlye
import styles from "../styles/Home.module.css"
// comps
import Product from "../components/Product"

export default function Home() {
  // fetch products from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY })
  const { data, error, fetching } = results

  // check from the data
  if (fetching) return <p>Loading...</p>
  if (error) return <p>Oh no...{error.message}</p>
  const products = data.products.data

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Gallery>
          {products.map((product) => (
            <Product
              product={product.attributes}
              key={product.attributes.slug}
            />
          ))}
        </Gallery>
      </main>
    </div>
  )
}
